### ISSUE TITLE
Accept hex strings without whitespace

### ISSUE THREAD

**Issue by alt-** [dgallegos/edidreader#3]
The EDIDs I receive aren't separated into pairs with whitespace in between (eg. 00 FF ..), but in one long string (eg. 00FF..)
It would be nice if I could just paste that in instead of having to do the splitting and joining myself.
Ie. `"00FF".match(/.{1,2}/g).join(' ')`

**Comment by flexarts** [comment]
+1!
Because for example the rawedid output in linux is without whitespaces.
E.g. for Vero 4k:
```
$ cat /sys/class/amhdmitx/amhdmitx0/rawedid
00ffffffffffff004c2d09050100000030120103801009780aee91a3544c99260f5054bdef80714f8100814081809500950fb3000101023a801871382d40582c4500a05a0000001e662150b051001b3040703600a05a0000001e000000fd00184b1a5117000a202020202020000000fc0053414d53554e470a2020202020016f020327f14b901f0413051403122021222309070783010000e2000fe305030167030c001000b82d011d007251d01e206e285500a05a0000001e011d00bc52d01e20b8285540a05a0000001e011d8018711c1620582c2500a05a0000009e011d80d0721c1620102c2580a05a0000009e000000000000000000000000000000001d
```

**Comment by FrankWu100** [comment]
Agree that, from xrandr also get without whitespace edid.
